import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { ReactNode } from "react";
import FileAccordion from "@/components/edit/FileAccordion";
import NavBar from "@/components/edit/NavBar";
import { GetSotryFolderList } from "@/services/storyFolder/service";

export const metadata: Metadata = {
  title: "Detail",
  description: "Generated by create next app",
};

export default async function NovelDetailLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: {
    novelId: string;
  };
}) {
  const cookieStore = cookies();
  const usertoken = cookieStore.get("next-auth.session-token");
  const { novelId } = params;

  const folderListData = await GetSotryFolderList({ novelId }, usertoken);

  return (
    <main>
      <header className="bg-blackAlpha-300 h-10 w-full">
        <div />
      </header>
      <div className="flex h-[calc(100vh-40px)] w-full">
        <NavBar />
        <FileAccordion folderList={folderListData} />
        {children}
      </div>
    </main>
  );
}
